name: builder_models
description: A starting point for Dart libraries or applications.
version: 1.0.7
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
